App\Entity\Account:
    exclusion_policy: ALL
    properties:
        name:
            expose: true
        email:
            expose: true
        phone:
            expose: true
        system_field:
            expose: true
        type:
            expose: true
        created_at:
            expose: true
