App\Entity\Campaign:
    exclusion_policy: ALL
    properties:
        campaign_type:
            expose: true
        name:
            expose: true
        custom_setting:
            expose: true
        message_end:
            expose: true
        created_at:
            expose: true
