fos_rest:
    view:
        view_response_listener: true
    serializer:
        serialize_null: true
    body_converter:
        enabled: true
    body_listener:
        enabled: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api',  priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }